"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['GameServer.py']
DATA_FILES = ['WerewolfTagClient.py',
 'PythonTidy.py',
 'Main.py',
 'GameState.py',
 'GameClient.py',
 'Game.py',
 'powerups',
 'player',
 'network',
 'Music',
 'INFX_125_Sprites-Music',
 'game',
 'base',
 'assets']
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
