# Window Properties
WINDOW_WIDTH = 640
WINDOW_HEIGHT = 480
WINDOW_FULLSCREEN = False

# Board Properties
BORDER_WIDTH = 640
BORDER_HEIGHT = 440

# Network Constants
NETWORK_HOST = "169.234.8.78"
NETWORK_PORT = 8887

# Game Model Properties
GAME_LENGTH = 100

# Sprite File Paths
SPRITE_FILEPATH_WEREWOLF = "assets/sprites/werewolf.png"
SPRITE_FILEPATH_HUMAN = "assets/sprites/human.png"
SPRITE_FILEPATH_SPEED = "assets/sprites/shoe.png"
SPRITE_FILEPATH_HAMMER = "assets/sprites/hammer.png"
SPRITE_FILEPATH_SHOVEL = "assets/sprites/shovel.png"
SPRITE_FILEPATH_HOLE = "assets/sprites/hole.png"
SPRITE_FILEPATH_BARN = "assets/sprites/barn.png"
SPRITE_FILEPATH_GAMEBACKGROUD = "assets/sprites/gamebackground.png"


# Directions States
DIRECTION_NONE = 0
DIRECTION_LEFT = 1
DIRECTION_RIGHT = 2
DIRECTION_UP = 3
DIRECTION_DOWN = 4

# Animation States
ANIMATION_NONE = DIRECTION_NONE
ANIMATION_MOVE_LEFT = DIRECTION_LEFT
ANIMATION_MOVE_RIGHT = DIRECTION_RIGHT
ANIMATION_MOVE_UP = DIRECTION_UP
ANIMATION_MOVE_DOWN = DIRECTION_DOWN
ANIMATION_TRANSFORM = 5

# Game States
GAME_STATE_MENU = 0
GAME_STATE_GAME = 1
GAME_STATE_EXIT = 2

# AI States
AI_EASY_MODE = 0
